apiVersion: v1
kind: Service
metadata:
  name: tomcatdemoapp-lb-service
spec:
  type: LoadBalancer
  selector:
    app: tomcatdemoapp
    department: tomcatdemoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
